version: '3.9'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /mnt/truenas/projects:/mnt/truenas/projects

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - /mnt/truenas/projects:/mnt/truenas/projects
